version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - devcontainer
  - pulumi
  - pymdownx
  - SAST
  - superfences
ignoreWords:
  - devcontainers
  - inlinehilite
  - mkdocs
  - mumforb
  - tmpfs
  - yzhang
import: []
